rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ip
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/acsd_2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/acsd_5
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ated
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/board_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/brctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/bridge
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/c_rehash
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cal_modify
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/chip_info_dump
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cmd_agent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cmld
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cmld_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cron
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/curl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/curl-config
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cwmp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/cwmp_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/dhcp_test
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/dhcp6c
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/dhcp6s
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/diagnose_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/dnsmasq
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/download_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ebtables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ethif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ethphxcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/evcom
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ez-ipupdate
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/fe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/fsck.hfsplus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ftps
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/fusermount
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/fw_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/fw_ctl.orig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/genl-ctrl-list
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/gpon_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/gponif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/gponmapcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_gpio_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_gpon_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_i2c_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_led_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_mcast_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_optical_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_qos_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_switch_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hal_wd_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hbs_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/heartbeat_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hw_nat
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/hw_pp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/igd_upnpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/igd_upnpd_v2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ip6tables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ip6tables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ip6tables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iptables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iptables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iptables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iptv_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iwconfig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/iwpriv
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/jshn
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/keventd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/klogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/led_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/led_wifi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/lsblk
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mcast_daemon
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mini_httpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mini_httpd.pem
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/minidlna
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mlabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mount.fuse
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mtd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mtk_itf_ppe_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/mtk_itf_switch_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/network_manager
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/networkmap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/nl_gpon_user
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/nmbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ntfs-3g
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ntfslabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ntp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/nvram
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/OneFi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/openssl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/pb_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ponmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/port_mirror
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ppe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/pppd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qcsapi_sockraw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qdmamgr_lan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qdmamgr_wan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qevt_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qinit
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qmonitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/qstart
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/queue_recv_and_send
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/radvd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/route_mark
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/rtmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sample_mtkitfqos
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sc_cli
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sifm
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/smbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/smbpasswd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/smbstatus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/smd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ssh-keygen
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sshd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/statd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/switch_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/switchmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sys
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sys_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/sys_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/syslogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/tc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/tcci
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/tce
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/tcwdog
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ubus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ubusd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/udhcp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/udhcpc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/udhcpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/udpecho
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/udpechoc_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/uevent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/ulockmgr_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/umci_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/umcid
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/upload_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/vgw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/vgw_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/voip_loader
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/voip_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/vsftpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/wifi_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/wifi_pb
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/wlan_proxy
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/wsc_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/wscd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/bin/xtables-multi

rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ip
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/acsd_2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/acsd_5
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ated
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/board_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/brctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/bridge
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/c_rehash
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cal_modify
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/chip_info_dump
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cmd_agent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cmld
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cmld_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cron
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/curl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/curl-config
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cwmp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/cwmp_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/dhcp_test
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/dhcp6c
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/dhcp6s
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/diagnose_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/dnsmasq
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/download_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ebtables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ethif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ethphxcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/evcom
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ez-ipupdate
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/fe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/fsck.hfsplus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ftps
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/fusermount
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/fw_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/fw_ctl.orig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/genl-ctrl-list
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/gpon_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/gponif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/gponmapcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_gpio_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_gpon_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_i2c_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_led_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_mcast_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_optical_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_qos_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_switch_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hal_wd_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hbs_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/heartbeat_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hw_nat
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/hw_pp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/igd_upnpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/igd_upnpd_v2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ip6tables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ip6tables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ip6tables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iptables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iptables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iptables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iptv_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iwconfig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/iwpriv
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/jshn
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/keventd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/klogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/led_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/led_wifi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/lsblk
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mcast_daemon
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mini_httpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mini_httpd.pem
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/minidlna
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mlabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mount.fuse
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mtd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mtk_itf_ppe_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/mtk_itf_switch_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/network_manager
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/networkmap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/nl_gpon_user
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/nmbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ntfs-3g
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ntfslabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ntp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/nvram
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/OneFi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/openssl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/pb_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ponmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/port_mirror
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ppe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/pppd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qcsapi_sockraw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qdmamgr_lan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qdmamgr_wan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qevt_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qinit
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qmonitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/qstart
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/queue_recv_and_send
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/radvd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/route_mark
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/rtmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sample_mtkitfqos
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sc_cli
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sifm
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/smbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/smbpasswd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/smbstatus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/smd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ssh-keygen
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sshd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/statd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/switch_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/switchmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sys
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sys_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/sys_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/syslogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/tc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/tcci
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/tce
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/tcwdog
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ubus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ubusd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/udhcp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/udhcpc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/udhcpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/udpecho
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/udpechoc_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/uevent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/ulockmgr_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/umci_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/umcid
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/upload_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/vgw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/vgw_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/voip_loader
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/voip_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/vsftpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/wifi_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/wifi_pb
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/wlan_proxy
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/wsc_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/wscd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/sbin/xtables-multi

rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ip
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/acsd_2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/acsd_5
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ated
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/board_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/brctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/bridge
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/c_rehash
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cal_modify
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/chip_info_dump
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cmd_agent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cmld
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cmld_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cron
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/curl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/curl-config
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cwmp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/cwmp_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/dhcp_test
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/dhcp6c
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/dhcp6s
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/diagnose_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/dnsmasq
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/download_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ebtables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ethif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ethphxcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/evcom
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ez-ipupdate
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/fe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/fsck.hfsplus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ftps
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/fusermount
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/fw_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/fw_ctl.orig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/genl-ctrl-list
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/gpon_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/gponif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/gponmapcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_gpio_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_gpon_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_i2c_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_led_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_mcast_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_optical_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_qos_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_switch_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hal_wd_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hbs_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/heartbeat_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hw_nat
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/hw_pp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/igd_upnpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/igd_upnpd_v2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ip6tables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ip6tables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ip6tables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iptables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iptables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iptables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iptv_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iwconfig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/iwpriv
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/jshn
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/keventd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/klogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/led_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/led_wifi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/lsblk
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mcast_daemon
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mini_httpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mini_httpd.pem
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/minidlna
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mlabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mount.fuse
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mtd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mtk_itf_ppe_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/mtk_itf_switch_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/network_manager
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/networkmap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/nl_gpon_user
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/nmbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ntfs-3g
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ntfslabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ntp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/nvram
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/OneFi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/openssl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/pb_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ponmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/port_mirror
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ppe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/pppd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qcsapi_sockraw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qdmamgr_lan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qdmamgr_wan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qevt_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qinit
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qmonitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/qstart
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/queue_recv_and_send
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/radvd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/route_mark
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/rtmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sample_mtkitfqos
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sc_cli
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sifm
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/smbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/smbpasswd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/smbstatus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/smd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ssh-keygen
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sshd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/statd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/switch_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/switchmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sys
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sys_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/sys_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/syslogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/tc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/tcci
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/tce
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/tcwdog
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ubus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ubusd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/udhcp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/udhcpc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/udhcpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/udpecho
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/udpechoc_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/uevent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/ulockmgr_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/umci_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/umcid
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/upload_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/vgw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/vgw_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/voip_loader
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/voip_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/vsftpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/wifi_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/wifi_pb
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/wlan_proxy
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/wsc_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/wscd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/bin/xtables-multi

rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ip
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/acsd_2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/acsd_5
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ated
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/board_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/brctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/bridge
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/c_rehash
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cal_modify
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/chip_info_dump
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cmd_agent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cmld
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cmld_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cron
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/curl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/curl-config
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cwmp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/cwmp_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/dhcp_test
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/dhcp6c
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/dhcp6s
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/diagnose_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/dnsmasq
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/download_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ebtables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ethif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ethphxcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/evcom
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ez-ipupdate
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/fe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/fsck.hfsplus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ftps
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/fusermount
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/fw_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/fw_ctl.orig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/genl-ctrl-list
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/gpon_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/gponif_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/gponmapcmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_gpio_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_gpon_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_i2c_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_led_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_mcast_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_optical_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_qos_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_switch_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hal_wd_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hbs_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/heartbeat_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hw_nat
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/hw_pp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/igd_upnpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/igd_upnpd_v2
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ip6tables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ip6tables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ip6tables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iptables
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iptables-restore
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iptables-save
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iptv_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iwconfig
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/iwpriv
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/jshn
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/keventd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/klogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/led_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/led_wifi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/lsblk
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mcast_daemon
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mini_httpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mini_httpd.pem
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/minidlna
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mlabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mount.fuse
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mtd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mtk_itf_ppe_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/mtk_itf_switch_sample
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/network_manager
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/networkmap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/nl_gpon_user
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/nmbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ntfs-3g
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ntfslabel
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ntp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/nvram
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/OneFi
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/openssl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/pb_ap
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ponmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/port_mirror
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ppe
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/pppd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qcsapi_sockraw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qdmamgr_lan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qdmamgr_wan
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qevt_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qinit
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qmonitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/qstart
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/queue_recv_and_send
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/radvd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/route_mark
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/rtmd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sample_mtkitfqos
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sc_cli
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sifm
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/smbd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/smbpasswd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/smbstatus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/smd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ssh-keygen
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sshd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/statd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/switch_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/switchmgr
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sys
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sys_client
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/sys_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/syslogd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/tc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/tcci
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/tce
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/tcwdog
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ubus
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ubusd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/udhcp
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/udhcpc
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/udhcpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/udpecho
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/udpechoc_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/uevent
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/ulockmgr_server
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/umci_ctl
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/umcid
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/upload_diag
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/vgw
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/vgw_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/voip_loader
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/voip_monitor
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/vsftpd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/wifi_init
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/wifi_pb
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/wlan_proxy
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/wsc_app
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/wscd
rm -rf /home/user/kit/images/busybox-1.32.0/_install/usr/sbin/xtables-multi
